# Generated by Django 6.0.2 on 2026-04-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datasheet", "0012_rename_duration_frequency_session_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="data_collector_id",
            field=models.IntegerField(),
        ),
    ]
