# Generated by Django 6.0.2 on 2026-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('bcba', 'BCBA'), ('rbt', 'RBT'), ('dsp', 'DSP')], default='dsp', max_length=10),
        ),
    ]
