# Generated by Django 6.0.2 on 2026-03-18 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_invitation_token_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
